/* The following code was generated by JFlex 1.4.3 on 31/12/23 14:48 */

package OLC1PROYECTO2.Analizadores;
import OLC1PROYECTO2.Estructuras.Excepcion;
import java_cup.runtime.*;
import java.util.ArrayList;
import java.util.List;



/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.4.3
 * on 31/12/23 14:48 from the specification file
 * <tt>src/main/java/OLC1PROYECTO2/Analizadores/lexico.jflex</tt>
 */
public class Lexico implements java_cup.runtime.Scanner {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\1\1\14\2\0\1\1\22\0\1\6\1\25\1\7\2\0"+
    "\1\45\1\41\1\13\1\53\1\54\1\23\1\42\1\50\1\43\1\4"+
    "\1\22\12\2\1\46\1\47\1\24\1\40\1\26\1\55\1\0\1\36"+
    "\1\33\1\37\1\32\1\27\1\16\2\3\1\35\2\3\1\34\1\56"+
    "\1\12\1\31\1\57\1\3\1\30\1\60\1\11\1\15\5\3\1\0"+
    "\1\10\1\0\1\44\2\0\1\36\1\33\1\37\1\32\1\27\1\16"+
    "\2\3\1\35\2\3\1\34\1\56\1\21\1\31\1\57\1\3\1\17"+
    "\1\60\1\20\1\15\5\3\1\51\1\5\1\52\uff82\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\1\3\1\4\1\5\3\1\1\4"+
    "\1\1\1\6\1\4\1\7\1\10\1\11\1\12\1\13"+
    "\5\4\1\14\1\1\1\15\1\16\1\17\1\20\1\21"+
    "\1\22\1\23\1\24\1\25\1\26\1\27\1\30\1\31"+
    "\1\0\1\32\1\33\2\0\1\34\1\0\1\35\1\32"+
    "\2\0\1\32\1\36\1\0\1\37\1\40\1\41\5\32"+
    "\1\42\1\43\1\44\1\22\1\31\1\45\1\32\1\46"+
    "\1\0\1\32\5\0\6\32\1\44\1\47\1\0\1\36"+
    "\1\0\6\32\1\0\1\32\1\50\4\32\1\0\1\51"+
    "\3\32\1\52\1\53\2\32\1\54\1\55";

  private static int [] zzUnpackAction() {
    int [] result = new int[110];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\61\0\142\0\223\0\304\0\61\0\365\0\u0126"+
    "\0\u0157\0\u0188\0\u01b9\0\61\0\u01ea\0\u021b\0\61\0\u024c"+
    "\0\u027d\0\u02ae\0\u02df\0\u0310\0\u0341\0\u0372\0\u03a3\0\u03d4"+
    "\0\u0405\0\61\0\61\0\61\0\u0436\0\61\0\u0467\0\61"+
    "\0\61\0\61\0\61\0\61\0\61\0\223\0\u0498\0\304"+
    "\0\61\0\u04c9\0\u04fa\0\61\0\u052b\0\61\0\u055c\0\u058d"+
    "\0\u05be\0\u05ef\0\u0620\0\u0651\0\61\0\61\0\61\0\u0682"+
    "\0\u06b3\0\u06e4\0\u0715\0\u0746\0\61\0\61\0\u0777\0\61"+
    "\0\u0498\0\61\0\u07a8\0\61\0\u07d9\0\u080a\0\u083b\0\u086c"+
    "\0\u089d\0\u08ce\0\u08ff\0\u0930\0\u0961\0\u0992\0\u09c3\0\u09f4"+
    "\0\u0a25\0\61\0\304\0\u0a56\0\u083b\0\u0a87\0\u0ab8\0\u0ae9"+
    "\0\u0b1a\0\u0b4b\0\u0b7c\0\u0bad\0\u0bde\0\u0c0f\0\304\0\u0c40"+
    "\0\u0c71\0\u0ca2\0\u0cd3\0\u0d04\0\304\0\u0d35\0\u0d66\0\u0d97"+
    "\0\304\0\304\0\u0dc8\0\u0df9\0\304\0\304";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[110];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\1\4\1\5\1\6\1\7\1\3\1\10"+
    "\1\11\1\12\1\5\1\13\1\14\1\5\1\15\1\5"+
    "\1\12\1\5\1\16\1\17\1\20\1\21\1\22\1\23"+
    "\2\5\1\24\1\25\1\5\1\26\1\5\1\27\1\30"+
    "\1\31\1\32\1\33\1\34\1\35\1\36\1\37\1\40"+
    "\1\41\1\42\1\43\1\44\1\45\3\5\62\0\1\3"+
    "\4\0\1\3\54\0\1\46\1\0\1\47\56\0\2\50"+
    "\5\0\2\50\2\0\5\50\5\0\11\50\16\0\3\50"+
    "\5\0\1\51\53\0\6\52\1\53\1\54\1\55\3\52"+
    "\1\0\44\52\7\0\1\56\2\0\2\56\5\0\1\56"+
    "\41\0\2\50\5\0\2\50\2\0\2\50\1\57\2\50"+
    "\5\0\1\50\1\57\7\50\16\0\3\50\10\60\1\61"+
    "\2\60\2\0\44\60\2\0\2\50\5\0\2\50\2\0"+
    "\5\50\5\0\7\50\1\62\1\50\16\0\3\50\22\0"+
    "\1\63\1\64\75\0\1\65\60\0\1\66\60\0\1\67"+
    "\22\0\2\50\5\0\1\50\1\70\2\0\4\50\1\70"+
    "\5\0\11\50\16\0\3\50\2\0\2\50\5\0\2\50"+
    "\2\0\5\50\5\0\2\50\1\71\6\50\16\0\3\50"+
    "\2\0\2\50\5\0\2\50\2\0\5\50\5\0\6\50"+
    "\1\72\2\50\16\0\3\50\2\0\2\50\5\0\2\50"+
    "\2\0\5\50\5\0\11\50\16\0\1\73\2\50\2\0"+
    "\2\50\5\0\2\50\2\0\5\50\5\0\7\50\1\74"+
    "\1\50\16\0\3\50\40\0\1\75\61\0\1\76\64\0"+
    "\1\77\27\0\1\100\46\0\1\101\2\0\2\101\52\0"+
    "\7\52\1\54\1\55\3\52\1\0\53\52\1\102\1\55"+
    "\3\52\1\0\44\52\7\0\5\52\4\0\2\52\41\0"+
    "\2\50\5\0\2\50\2\0\1\103\4\50\5\0\11\50"+
    "\16\0\3\50\13\0\1\104\54\0\1\60\3\0\1\60"+
    "\1\0\1\105\1\0\3\60\41\0\2\50\5\0\2\50"+
    "\2\0\5\50\5\0\5\50\1\106\3\50\16\0\3\50"+
    "\14\63\1\0\44\63\23\107\1\110\1\111\1\112\1\113"+
    "\32\107\2\0\2\50\5\0\1\114\1\50\2\0\3\50"+
    "\1\114\1\50\5\0\11\50\16\0\3\50\2\0\2\50"+
    "\5\0\2\50\2\0\5\50\5\0\4\50\1\115\4\50"+
    "\16\0\3\50\2\0\2\50\5\0\1\50\1\116\2\0"+
    "\4\50\1\116\5\0\11\50\16\0\3\50\2\0\2\50"+
    "\5\0\2\50\2\0\5\50\5\0\11\50\16\0\1\50"+
    "\1\117\1\50\2\0\2\50\5\0\2\50\2\0\2\50"+
    "\1\120\2\50\5\0\1\50\1\120\1\50\1\121\5\50"+
    "\16\0\3\50\14\0\1\122\46\0\2\50\5\0\2\50"+
    "\2\0\5\50\5\0\1\123\10\50\16\0\3\50\2\0"+
    "\1\124\13\0\1\124\10\0\1\124\2\0\2\124\2\0"+
    "\2\124\23\0\2\50\5\0\2\50\2\0\5\50\5\0"+
    "\11\50\16\0\2\50\1\103\23\107\1\110\1\111\1\112"+
    "\55\107\1\125\1\110\1\111\1\112\33\107\25\64\1\0"+
    "\33\64\23\107\1\110\1\126\1\112\1\113\32\107\25\0"+
    "\2\64\34\0\2\50\5\0\2\50\2\0\5\50\5\0"+
    "\1\127\10\50\16\0\3\50\2\0\2\50\5\0\2\50"+
    "\2\0\5\50\5\0\5\50\1\130\3\50\16\0\3\50"+
    "\2\0\2\50\5\0\2\50\2\0\5\50\5\0\7\50"+
    "\1\131\1\50\16\0\3\50\2\0\2\50\5\0\2\50"+
    "\2\0\2\50\1\132\2\50\5\0\1\50\1\132\7\50"+
    "\16\0\3\50\2\0\2\50\5\0\2\50\2\0\5\50"+
    "\5\0\7\50\1\133\1\50\16\0\3\50\2\0\2\50"+
    "\5\0\2\50\2\0\5\50\5\0\1\134\10\50\16\0"+
    "\3\50\2\0\1\135\13\0\1\135\10\0\1\135\2\0"+
    "\2\135\2\0\2\135\21\0\23\107\1\110\1\126\1\112"+
    "\33\107\2\0\2\50\5\0\2\50\2\0\2\50\1\136"+
    "\2\50\5\0\1\50\1\136\7\50\16\0\3\50\2\0"+
    "\2\50\5\0\2\50\2\0\5\50\5\0\1\137\10\50"+
    "\16\0\3\50\2\0\2\50\5\0\2\50\2\0\2\50"+
    "\1\140\2\50\5\0\1\50\1\140\7\50\16\0\3\50"+
    "\2\0\2\50\5\0\2\50\2\0\5\50\5\0\6\50"+
    "\1\141\2\50\16\0\3\50\2\0\2\50\5\0\2\50"+
    "\2\0\5\50\5\0\10\50\1\142\16\0\3\50\2\0"+
    "\2\50\5\0\1\50\1\143\2\0\4\50\1\143\5\0"+
    "\11\50\16\0\3\50\2\0\1\144\13\0\1\144\10\0"+
    "\1\144\2\0\2\144\2\0\2\144\23\0\2\50\5\0"+
    "\2\50\2\0\5\50\5\0\2\50\1\145\6\50\16\0"+
    "\3\50\2\0\2\50\5\0\2\50\2\0\5\50\5\0"+
    "\6\50\1\146\2\50\16\0\3\50\2\0\2\50\5\0"+
    "\2\50\2\0\5\50\5\0\11\50\16\0\1\147\2\50"+
    "\2\0\2\50\5\0\1\150\1\50\2\0\3\50\1\150"+
    "\1\50\5\0\11\50\16\0\3\50\2\0\2\50\5\0"+
    "\2\50\2\0\5\50\5\0\7\50\1\151\1\50\16\0"+
    "\3\50\2\0\1\60\13\0\1\60\10\0\1\60\2\0"+
    "\2\60\2\0\2\60\23\0\2\50\5\0\2\50\2\0"+
    "\5\50\5\0\2\50\1\152\6\50\16\0\3\50\2\0"+
    "\2\50\5\0\2\50\2\0\5\50\5\0\6\50\1\153"+
    "\2\50\16\0\3\50\2\0\2\50\5\0\2\50\2\0"+
    "\5\50\5\0\1\154\10\50\16\0\3\50\2\0\2\50"+
    "\5\0\2\50\2\0\2\50\1\155\2\50\5\0\1\50"+
    "\1\155\7\50\16\0\3\50\2\0\2\50\5\0\2\50"+
    "\2\0\2\50\1\156\2\50\5\0\1\50\1\156\7\50"+
    "\16\0\3\50";

  private static int [] zzUnpackTrans() {
    int [] result = new int[3626];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\3\1\1\11\5\1\1\11\2\1\1\11"+
    "\12\1\3\11\1\1\1\11\1\1\6\11\1\1\1\0"+
    "\1\1\1\11\2\0\1\11\1\0\1\11\1\1\2\0"+
    "\2\1\1\0\3\11\5\1\2\11\1\1\1\11\1\1"+
    "\1\11\1\1\1\11\1\0\1\1\5\0\6\1\1\11"+
    "\1\1\1\0\1\1\1\0\6\1\1\0\6\1\1\0"+
    "\12\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[110];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;

  /* user code: */
    public List<Excepcion> Errors = new ArrayList<>();
    public int cont = 1;


  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public Lexico(java.io.Reader in) {
      yyline = 1;
    yychar = 1;
    this.zzReader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  public Lexico(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }

  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 156) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzCurrentPos*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
    }

    /* finally: fill the buffer with new input */
    int numRead = zzReader.read(zzBuffer, zzEndRead,
                                            zzBuffer.length-zzEndRead);

    if (numRead > 0) {
      zzEndRead+= numRead;
      return false;
    }
    // unlikely but not impossible: read 0 characters, but not at end of stream    
    if (numRead == 0) {
      int c = zzReader.read();
      if (c == -1) {
        return true;
      } else {
        zzBuffer[zzEndRead++] = (char) c;
        return false;
      }     
    }

	// numRead < 0
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      yychar+= zzMarkedPosL-zzStartRead;

      boolean zzR = false;
      for (zzCurrentPosL = zzStartRead; zzCurrentPosL < zzMarkedPosL;
                                                             zzCurrentPosL++) {
        switch (zzBufferL[zzCurrentPosL]) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          zzR = false;
          break;
        case '\r':
          yyline++;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
          }
          break;
        default:
          zzR = false;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL)
            zzInput = zzBufferL[zzCurrentPosL++];
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = zzBufferL[zzCurrentPosL++];
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          int zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 12: 
          { return new Symbol(sym.ASIGNACION,yyline,yychar, yytext());
          }
        case 46: break;
        case 35: 
          { return new Symbol(sym.AND,yyline,yychar, yytext());
          }
        case 47: break;
        case 33: 
          { return new Symbol(sym.MAYORIGUAL,yyline,yychar, yytext());
          }
        case 48: break;
        case 42: 
          { return new Symbol(sym.STRING,yyline,yychar, yytext());
          }
        case 49: break;
        case 26: 
          { return new Symbol(sym.IDENTIFICADOR, yyline, yychar, yytext());
          }
        case 50: break;
        case 34: 
          { return new Symbol(sym.IGUAL,yyline,yychar, yytext());
          }
        case 51: break;
        case 23: 
          { return new Symbol(sym.PARDER,yyline,yychar, yytext());
          }
        case 52: break;
        case 7: 
          { return new Symbol(sym.DIV,yyline,yychar, yytext());
          }
        case 53: break;
        case 37: 
          { return new Symbol(sym.ESPACIO,yyline,yychar, yytext());
          }
        case 54: break;
        case 18: 
          { return new Symbol(sym.PTCOMA,yyline,yychar, yytext());
          }
        case 55: break;
        case 5: 
          { return new Symbol(sym.PT,yyline,yychar, yytext());
          }
        case 56: break;
        case 39: 
          { return new Symbol(sym.BOOL,yyline,yychar, yytext());
          }
        case 57: break;
        case 19: 
          { return new Symbol(sym.COMA,yyline,yychar, yytext());
          }
        case 58: break;
        case 45: 
          { return new Symbol(sym.CHAR,yyline,yychar, yytext());
          }
        case 59: break;
        case 13: 
          { return new Symbol(sym.SUMA,yyline,yychar, yytext());
          }
        case 60: break;
        case 10: 
          { return new Symbol(sym.NOT,yyline,yychar, yytext());
          }
        case 61: break;
        case 24: 
          { return new Symbol(sym.INTERR,yyline,yychar, yytext());
          }
        case 62: break;
        case 32: 
          { return new Symbol(sym.DIFERENCIA,yyline,yychar, yytext());
          }
        case 63: break;
        case 3: 
          { return new Symbol(sym.DIGITO,yyline,yychar, yytext());
          }
        case 64: break;
        case 29: 
          { return new Symbol(sym.ESPECIAL,yyline,yychar, yytext());
          }
        case 65: break;
        case 11: 
          { return new Symbol(sym.MAYOR,yyline,yychar, yytext());
          }
        case 66: break;
        case 14: 
          { return new Symbol(sym.RESTA,yyline,yychar, yytext());
          }
        case 67: break;
        case 27: 
          { return new Symbol(sym.OR,yyline,yychar, yytext());
          }
        case 68: break;
        case 6: 
          { yychar=1;
          }
        case 69: break;
        case 20: 
          { return new Symbol(sym.LLAVEIZ,yyline,yychar, yytext());
          }
        case 70: break;
        case 31: 
          { return new Symbol(sym.MENORIGUAL,yyline,yychar, yytext());
          }
        case 71: break;
        case 9: 
          { return new Symbol(sym.MENOR,yyline,yychar, yytext());
          }
        case 72: break;
        case 1: 
          { Errors.add(new Excepcion("Léxico", "El caracter "+yytext()+" no pertenece al lenguaje", yyline, yychar));
    
    cont++;
          }
        case 73: break;
        case 43: 
          { return new Symbol(sym.BOOLEAN,yyline,yychar, yytext());
          }
        case 74: break;
        case 17: 
          { return new Symbol(sym.DOSPT,yyline,yychar, yytext());
          }
        case 75: break;
        case 8: 
          { return new Symbol(sym.MULT,yyline,yychar, yytext());
          }
        case 76: break;
        case 15: 
          { return new Symbol(sym.POTE,yyline,yychar, yytext());
          }
        case 77: break;
        case 30: 
          { return new Symbol(sym.COMENTARIO,yyline,yychar, yytext());
          }
        case 78: break;
        case 41: 
          { return new Symbol(sym.INT,yyline,yychar, yytext());
          }
        case 79: break;
        case 38: 
          { return new Symbol(sym.CARACTERES,yyline,yychar, yytext());
          }
        case 80: break;
        case 21: 
          { return new Symbol(sym.LLAVEDER,yyline,yychar, yytext());
          }
        case 81: break;
        case 22: 
          { return new Symbol(sym.PARIZQ,yyline,yychar, yytext());
          }
        case 82: break;
        case 36: 
          { return new Symbol(sym.FIN,yyline,yychar, yytext());
          }
        case 83: break;
        case 28: 
          { return new Symbol(sym.PARRAF,yyline,yychar, yytext());
          }
        case 84: break;
        case 16: 
          { return new Symbol(sym.MODULO,yyline,yychar, yytext());
          }
        case 85: break;
        case 44: 
          { return new Symbol(sym.RIMPRIMIR,yyline,yychar, yytext());
          }
        case 86: break;
        case 25: 
          { return new Symbol(sym.DECIMAL,yyline,yychar, yytext());
          }
        case 87: break;
        case 40: 
          { return new Symbol(sym.DOUBLE,yyline,yychar, yytext());
          }
        case 88: break;
        case 4: 
          { return new Symbol(sym.LETRA,yyline,yychar, yytext());
          }
        case 89: break;
        case 2: 
          { 
          }
        case 90: break;
        default: 
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
            zzDoEOF();
              { return new java_cup.runtime.Symbol(sym.EOF); }
          } 
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
