
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package OLC1PROYECTO2.Analizadores;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int PT = 25;
  public static final int ESPECIAL = 34;
  public static final int DIFERENCIA = 8;
  public static final int RIMPRIMIR = 41;
  public static final int MULT = 18;
  public static final int CHAR = 5;
  public static final int LLAVEIZ = 27;
  public static final int DOUBLE = 3;
  public static final int RESTA = 17;
  public static final int LLAVEDER = 28;
  public static final int CARACTERES = 40;
  public static final int INTERR = 29;
  public static final int INT = 2;
  public static final int DOSPT = 22;
  public static final int FIN = 23;
  public static final int IDENTIFICADOR = 36;
  public static final int NOT = 15;
  public static final int MENORIGUAL = 10;
  public static final int AND = 14;
  public static final int IGUAL = 7;
  public static final int LETRA = 32;
  public static final int OR = 13;
  public static final int ESPACIO = 33;
  public static final int DIV = 19;
  public static final int SUMA = 16;
  public static final int UMENOS = 44;
  public static final int MAYORIGUAL = 12;
  public static final int PARIZQ = 42;
  public static final int DECIMAL = 39;
  public static final int EOF = 0;
  public static final int BOOLEAN = 4;
  public static final int error = 1;
  public static final int DIGITO = 30;
  public static final int COMA = 26;
  public static final int POTE = 20;
  public static final int COMENTARIO = 38;
  public static final int MODULO = 21;
  public static final int MENOR = 9;
  public static final int ASIGNACION = 35;
  public static final int MAYOR = 11;
  public static final int PARRAF = 37;
  public static final int SIGNO = 31;
  public static final int PTCOMA = 24;
  public static final int STRING = 6;
  public static final int PARDER = 43;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "INT",
  "DOUBLE",
  "BOOLEAN",
  "CHAR",
  "STRING",
  "IGUAL",
  "DIFERENCIA",
  "MENOR",
  "MENORIGUAL",
  "MAYOR",
  "MAYORIGUAL",
  "OR",
  "AND",
  "NOT",
  "SUMA",
  "RESTA",
  "MULT",
  "DIV",
  "POTE",
  "MODULO",
  "DOSPT",
  "FIN",
  "PTCOMA",
  "PT",
  "COMA",
  "LLAVEIZ",
  "LLAVEDER",
  "INTERR",
  "DIGITO",
  "SIGNO",
  "LETRA",
  "ESPACIO",
  "ESPECIAL",
  "ASIGNACION",
  "IDENTIFICADOR",
  "PARRAF",
  "COMENTARIO",
  "DECIMAL",
  "CARACTERES",
  "RIMPRIMIR",
  "PARIZQ",
  "PARDER",
  "UMENOS"
  };
}

